# Sử dụng Docker image TensorFlow GPU
FROM tensorflow/tensorflow:latest-gpu

# Thiết lập thư mục làm việc bên trong container
WORKDIR /app

# Sao chép requirements cho updater và cài đặt phụ thuộc
COPY updater-requirements.txt .
RUN pip install --upgrade pip setuptools \
    && pip install --timeout=360 --no-cache-dir -r updater-requirements.txt

# Sao chép mã nguồn ứng dụng
COPY update_app.py app_config.py app_utils.py /app/

# Đảm bảo TensorFlow có thể sử dụng GPU (nếu cần
